version: '3.3'
services:
  postgresdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: 'user'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - '5432:5432'